# Generated by Django 5.0.7 on 2024-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('tgid', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('referal', models.CharField(max_length=512)),
            ],
        ),
    ]
