# Generated by Django 5.0.7 on 2024-07-18 21:12

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('course', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tgid', models.CharField(editable=False, max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('referal_id', models.CharField(max_length=512)),
                ('balance', models.IntegerField(default=500)),
                ('last_visit', models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 12, 39, 824105))),
            ],
        ),
        migrations.CreateModel(
            name='User_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('is_daily', models.BooleanField(default=True)),
                ('is_onetime', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dal.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dal.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(through='dal.User_Task', to='dal.user'),
        ),
    ]
