# Generated by Django 5.0.7 on 2024-07-18 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='done_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 15, 13, 937229)),
        ),
    ]
