# Generated by Django 5.0.7 on 2024-07-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referal',
            new_name='referal_id',
        ),
    ]
