# Generated by Django 5.0.7 on 2024-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0002_rename_referal_user_referal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCourse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('course', models.FloatField()),
            ],
        ),
    ]
