# Generated by Django 5.0.7 on 2024-07-18 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0003_alter_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 25, 35, 92694)),
        ),
    ]
