# Generated by Django 5.0.7 on 2024-07-18 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0004_alter_user_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task',
            name='is_daily',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='is_onetime',
        ),
        migrations.AddField(
            model_name='task',
            name='is_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_onetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 26, 19, 608044)),
        ),
    ]
