# Generated by Django 5.0.7 on 2024-07-18 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0005_remove_user_task_is_daily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 9, 56, 581399, tzinfo=datetime.timezone.utc)),
        ),
    ]
