# Generated by Django 5.0.7 on 2024-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0007_alter_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
