# Generated by Django 5.0.7 on 2024-07-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0008_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_daily',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_onetime',
        ),
        migrations.AddField(
            model_name='task',
            name='params',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
